### PR TITLE
Firebase auth

### LINKED ISSUE #3: Add Firebase Sign In and Authentication
Need to add Firebase sign in form so users can create accounts for the forum

### PR DESCRIPTION
**Pull request by skeshavaa**
Added firebase-auth with React router as well. 

Now the Home and Explore page can be added using react router based off weather the user is logged in or not

### CODE REVIEW

**Review by anjali-001 — APPROVED** [review]

**Comment by SiddeshSambasivam** [comment]
Hey @skeshavaa! 

I have a few comments on the PR.

1. It's better to create an auth component and use react context to manage the authentication state across all the pages. Right now, I see that the authentication state is local to the `app.js`. 

2. Also, pls add route guarding to all the pages.

**References:**
* [How to setup Route Guarding ](https://www.youtube.com/watch?v=unr4s3jd9qA)
* [Setting up protected routes](https://medium.com/swlh/firebase-authentication-and-react-protecting-your-routes-18d6da04b4c3)

**Review by anjali-001 — APPROVED** [review]

**Comment by SiddeshSambasivam** [comment]
@anjali-001 and @skeshavaa I'll work on the same branch for the route guarding

**Comment by SiddeshSambasivam** [comment]
@anjali-001 and @skeshavaa I'll work on the same branch for the route guarding

**Comment by SiddeshSambasivam** [comment]
## What feature was added?

* Added a react context to use the state of authentication across all the components

## How to use it?

```javascript

import { AuthContext } from '../../auth';
import React, { useContext } from 'react';

/* Inside any component */
const currentUser = useContext(AuthContext);


```

**Review by SiddeshSambasivam — APPROVED** [review]

**Review by anjali-001 — APPROVED** [review]

**Pull request merged**
